-- Create Memories Table
create table if not exists osiris_memories (
  id bigint generated by default as identity primary key,
  content text not null,
  category text default 'general',
  importance int default 1,
  metadata jsonb default '{}'::jsonb,
  timestamp timestamptz default timezone('utc'::text, now())
);

-- Create Interaction Logs Table
create table if not exists osiris_logs (
  id bigint generated by default as identity primary key,
  role text,
  content text,
  metadata jsonb default '{}'::jsonb,
  timestamp timestamptz default timezone('utc'::text, now())
);

-- Enable Row Level Security (RLS)
alter table osiris_memories enable row level security;
alter table osiris_logs enable row level security;

-- Create Policy: Allow Service Role (Full Access)
create policy "Enable full access for service role" on osiris_memories
  for all using ( auth.role() = 'service_role' );

create policy "Enable full access for service role" on osiris_logs
  for all using ( auth.role() = 'service_role' );

-- Create Policy: Allow Anon Read (Optional, for testing)
create policy "Allow public read access" on osiris_memories
  for select using ( true );
